parameters:
    coreshop.form.type.gateway_config.validation_groups: [fotobuch]

services:
    CoreShop\Bundle\PayumPaymentBundle\Form\Extension\PaymentProviderTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: CoreShop\Bundle\PaymentBundle\Form\Type\PaymentProviderType }

    CoreShop\Bundle\PayumPaymentBundle\Form\Extension\PaymentProviderChoiceTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: CoreShop\Bundle\PaymentBundle\Form\Type\PaymentProviderChoiceType }

    CoreShop\Bundle\PayumPaymentBundle\Form\Type\GatewayConfigType:
        arguments:
            - '%coreshop.model.gateway_config.class%'
            - '%coreshop.form.type.gateway_config.validation_groups%'
            - '@coreshop.form_registry.payum_gateway_config'
        tags:
            - { name: form.type }
